<?php
// Security constant required to run the classes so that no class can be directly run out of framework.
define('OMTECH','Om Technologies Base Framework');

//uncomment to see php erroros
//error_reporting(E_ALL); ini_set('display_errors', '1');

//Absolute path of application.
define('ABS_ROOT_PATH', 'C:/wamp/www/Colt_POS/');

//Absolute path of domain root dir
define('DOMAIN_PATH', 'C:/wamp/www/Colt_POS/');

//Root url where application is installed.
define('DOMAIN_URL', 'http://localhost/Colt_POS/');

//Database Settings
define('DBHOST', 'localhost:3306');
define('DBUSER', 'root');
define('DBPASS', 'rootpassword');
define('DBNAME', 'colt_db');
//

//class directory path
define('CLASS_PATH', ABS_ROOT_PATH . 'lib/classes/');
//base classes directiory path.
define('BASE_CLASS_PATH', CLASS_PATH . 'omfs/');

//frontend pages path
define('PAGES_PATH', ABS_ROOT_PATH . 'pages/');

//frontend controller path
define('PROCESS_PATH', ABS_ROOT_PATH . 'process/');

define('PEAR_PATH', ABS_ROOT_PATH . 'PEAR/');

//frontend path where user files are generated by system. eg. user reports/ customer invoices etc.
define('GENERATED_PATH', ABS_ROOT_PATH . 'generated/');

//System generated report files path
define('REPORTS_PATH', GENERATED_PATH . 'reports/');

//Path for logs directory and log files used by system to log errors.
define('LOG_PATH', GENERATED_PATH . 'logs/');
define('DB_LOG_FILE', LOG_PATH . 'dblogs.php');
define('LOG_FILE', LOG_PATH . 'logs.php');


//Include path where CSS, JS and Images(not user / customer pics but only system used images) reside.
define('INCLUDES_PATH', ABS_ROOT_PATH . 'includes/');
define('IMAGE_PATH', INCLUDES_PATH . 'img/');
define('CSS_PATH', INCLUDES_PATH . 'css/');
define('JS_PATH', INCLUDES_PATH . 'js/');

//Path where user uploaded pics and docs reside.
define('UPLOADS_PATH', ABS_ROOT_PATH . 'uploads/');
define('PICS_PATH',UPLOADS_PATH.'pics/');
define('THUMBS_PATH',PICS_PATH.'thumbs/');

//Admin folder path
define('ADMIN_PATH', ABS_ROOT_PATH . 'admin/');

//Path for admin pages (views)
define('ADMIN_PAGES_PATH', ADMIN_PATH . 'pages/');

//Path for admin controller php files.
define('ADMIN_PROCESS_PATH', ADMIN_PATH . 'process/');

//Path for admin generated reports.
define('ADMIN_GENERATED_PATH', ADMIN_PATH . 'generated/');
define('ADMIN_REPORTS_PATH', ADMIN_GENERATED_PATH . 'reports/');

//URLs relative to domain url but in absolute terms for images, css, Js, pages (views) and process (controllers)
define('IMAGE_URL', DOMAIN_URL . 'includes/img/');
define('CSS_URL', DOMAIN_URL . 'includes/css/');
define('JS_URL', DOMAIN_URL . 'includes/js/');
define('GIS_URL', DOMAIN_URL . 'includes/gis_data/');
define('PAGES_URL', DOMAIN_URL . 'pages/');
define('PROCESS_URL', DOMAIN_URL . 'process/');
define('UPLOAD_URL', DOMAIN_URL . 'uploads/');
define('PIC_URL', UPLOAD_URL . 'pics/');
define('THUMB_URL', PIC_URL . 'thumbs/');


//URL for admin directory, pages and processes (controllers)
define('ADMIN_URL', DOMAIN_URL . 'admin/');
define('ADMIN_PAGES_URL', ADMIN_URL . 'pages/');
define('ADMIN_PROCESS_URL', ADMIN_URL . 'process/');



/* DO NOT EDIT BELOW THIS LINE */
//Connect to database

//Import db class file.
require_once(CLASS_PATH . 'db.class.php');

//Instantiate DB class.
$DB = new DB(DBHOST, DBUSER, DBPASS, DBNAME);

//If failed to instantiate DB class then exit application.
if(!$DB) {
	trigger_error('Failed to connect to Database. Cannot Continue');
	exit();
}

//Setup the TIMEZONE
date_default_timezone_set('Africa/Johannesburg');

//Autoload Classes
function __autoload($className){
	$className = strtolower($className);
	$className = str_replace('class','',$className);
	if(file_exists(CLASS_PATH.strtolower($className).'.class.php')) {
		require_once(CLASS_PATH.strtolower($className).'.class.php');
	}
}


function printjs($script) {
    print "\n\n <script language='javascript'> \n\n $script \n\n script>\n\n";
}

?>